[workspace]
default-members = ["odilia"]
members = [
	"cache",
  "common",
  "input",
  "odilia",
]

[profile.release]
lto = true
codegen-units = 1 # Reduce codegen units for better optimizations (from swhkd)

[workspace.metadata.release]
allow-branch = ["main"]
# By default, crates will not be released or published
# These are overridden on a crate-by-crate basis
release = false
publish = false
shared-version = true
consolidate-commits = true
consolidate-pushes = true
pre-release-commit-message = "Release Odilia version {{version}}"
post-release-commit-message = "Post release version bump: version {{next_version}}"
tag-message = "{{crate_name}} version {{version}}"
dev-version-ext = "dev"
dev-version = true
pre-release-hook = ["cargo", "fmt"]
dependent-version = "upgrade"

[workspace.dependencies]
atspi = { path = "../atspi/atspi/" }#git = "https://github.com/odilia-app/atspi", branch = "types_crate_v2", default-features = false, features = ["tokio", "unstable-proxy-traits"] }
atspi-client = { path = "../atspi/atspi-client" }#git = "https://github.com/odilia-app/atspi", default-features = false, branch = "types_crate_v2" }
atspi-proxies = { path = "../atspi/atspi-proxies/"}#git = "https://github.com/odilia-app/atspi", default-features = false, branch = "types_crate_v2" }
atspi-common = { path = "../atspi/atspi-common/" }#git = "https://github.com/odilia-app/atspi", default-features = false, branch = "types_crate_v2" }
atspi-connection = { path = "../atspi/atspi-connection/" }#git = "https://github.com/odilia-app/atspi", default-features = false, branch = "types_crate_v2" }
odilia-common = { version = "0.3.0", path = "./common" }
odilia-cache = { version = "0.3.0", path = "./cache" }
eyre = "0.6.8"
nix = "0.26.2"
serde_json = "1.0.89"
ssip-client-async = { default-features = false, features = ["tokio"], version = "0.10.0" }
tokio = { version = "^1.22.0", default-features = false, features = ["sync", "macros", "rt", "signal", "tracing"] }
tracing = "^0.1.37"
tracing-log = "^0.1.3"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["env-filter", "parking_lot"] }
tracing-error = "^0.2.0"
tracing-tree = "^0.2.2"
zbus = { version = "^3.6.2", default-features = false, features = ["tokio"] }
serde_plain = "1.0.1"

