[target.aarch64-unknown-linux-musl]
dockerfile = "podman/aarch64-unknown-linux-musl.Containerfile"
[target.aarch64-unknown-linux-gnu]
dockerfile = "podman/aarch64-unknown-linux-gnu.Containerfile"
[target.x86_64-unknown-linux-musl]
dockerfile = "podman/x86_64-unknown-linux-musl.Containerfile"
[target.x86_64-unknown-linux-gnu]
dockerfile = "podman/x86_64-unknown-linux-gnu.Containerfile"
