[package]
name = "odilia-tower"
version = "0.1.0"
edition = "2021"

[dependencies]
atspi.workspace = true
atspi-common.workspace = true
derived-deref = "2.1.0"
futures = "0.3.31"
futures-concurrency.workspace = true
odilia-cache.workspace = true
odilia-common.workspace = true
refinement = "0.5.0"
tokio.workspace = true
tower = { version = "0.5.2", features = ["util"] }
tracing.workspace = true
zbus.workspace = true
