[package]
name = "odilia-common"
version = "0.3.0"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Common algorithms and data structures shared by multiple Odilia screen reader crates."
license = "GPL-3.0-only" # Not gpl-3-or-later
readme = "README.md"
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["screen-reader", "accessibility", "a11y", "data-structures", "linux"]
categories = ["accessibility"]
edition = "2021"

[features]
default = []
zbus = ["dep:zbus"]
proxies = ["dep:atspi-proxies"]

[dependencies]
atspi-common.workspace = true
atspi-proxies = { workspace = true, optional = true }
ssip-common.workspace = true
bitflags = "1.3.2"
dashmap.workspace = true
fxhash.workspace = true
serde = "1.0.147"
thiserror = "1.0.37"
tini = "^1.3.0"
smartstring.workspace = true
serde_plain.workspace = true
zvariant.workspace = true
zbus_names.workspace = true
zbus = { workspace = true, optional = true }
